### PR TITLE
changed dart:html to use flutter_user_agent instead

### PR DESCRIPTION
**Pull request by knyghtryda**
dart:html is incompatible with mobile, so I switched it out for flutter_user_agent since it seems to provide the user agent info you are looking for.  I'm not sure what web support you are looking for though, as I don't see much need to use this plugin for a web deployment.

### CODE REVIEW

**Comment by bsutton** [comment]
Any chance of seeing a merge and release based on this commit?

**Comment by voivoed** [comment]
@rodydavis it's been months, can we get this merged please?

**Comment by rodydavis** [comment]
Sure thing!

**Comment by voivoed** [comment]
@rodydavis ...and released? sorry :-)

**Comment by rodydavis** [comment]
Working on publishing now

**Comment by rodydavis** [comment]
Published 2.1.1

**Pull request merged**
